CREATE DATABSE GESTAO_USUARIOS_2RP;
GO

USE GESTAO_USUARIOS_2RP;
GO

CREATE TABLE TIPOUSUARIO(
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	nomeTipoUsuario VARCHAR(40) UNIQUE NOT NULL
);
GO

CREATE TABLE USUARIO(
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nomeUsuario VARCHAR(100) NOT NULL,
	email VARCHAR(256) UNIQUE NOT NULL,
	senha VARCHAR(10) NOT NULL
);
GO